In [1]:
# import library yang diperlukan
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# import dataset dari file lokal 
data = pd.read_csv('dataset/drug200.csv') 
data.head() 

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [3]:
#EDA
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [4]:
data.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [5]:
numerical_features = [feature for feature in data.columns 
                      if data[feature].dtypes != 'O']
print("The length of Numerical_values is :",
      len(numerical_features))
data[numerical_features].head()



The length of Numerical_values is : 2


Age  Na_to_K
0   23   25.355
1   47   13.093
2   47   10.114
3   28    7.798
4   61   18.043

In [6]:
categorical_features = [feature for feature in data.columns 
                        if data[feature].dtypes == 'O']
print("The length of Numerical_values is :",
      len(categorical_features))
data[categorical_features].head()


The length of Numerical_values is : 4


Sex      BP Cholesterol   Drug
0   F    HIGH        HIGH  DrugY
1   M     LOW        HIGH  drugC
2   M     LOW        HIGH  drugC
3   F  NORMAL        HIGH  drugX
4   F     LOW        HIGH  DrugY

In [7]:
#melihat kategori tiap data categorical

for i in categorical_features:
    print(data[i].unique())

['F' 'M']
['HIGH' 'LOW' 'NORMAL']
['HIGH' 'NORMAL']
['DrugY' 'drugC' 'drugX' 'drugA' 'drugB']


In [8]:
#mengubah data kategorik ke numerik
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

for feature in categorical_features:
    print(data[feature].unique())
    data[feature]=label_encoder.fit_transform(data[feature])
    print(data[feature].unique())

['F' 'M']
[0 1]
['HIGH' 'LOW' 'NORMAL']
[0 1 2]
['HIGH' 'NORMAL']
[0 1]
['DrugY' 'drugC' 'drugX' 'drugA' 'drugB']
[0 3 4 1 2]


In [9]:
data.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0

In [10]:
#menyiapkan data x dan y
x = data.drop(['Drug'], axis = 1) 
y = data['Drug'] 

print(x) 
print(y) 

     Age  Sex  BP  Cholesterol  Na_to_K
0     23    0   0            0   25.355
1     47    1   1            0   13.093
2     47    1   1            0   10.114
3     28    0   2            0    7.798
4     61    0   1            0   18.043
..   ...  ...  ..          ...      ...
195   56    0   1            0   11.567
196   16    1   1            0   12.006
197   52    1   2            0    9.894
198   23    1   2            1   14.020
199   40    0   1            1   11.349

[200 rows x 5 columns]
0      0
1      3
2      3
3      4
4      0
      ..
195    3
196    3
197    4
198    4
199    4
Name: Drug, Length: 200, dtype: int32


In [11]:
#Membagi dataset menjadi data latih dan data uji
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x,
                                                y, 
                                                test_size = 0.25, 
                                                random_state=0)
#cetak dimensi tiap variabel
print(f'x shape {x.shape}')
print(f'y shape {y.shape}')
print(f'x_train shape {x_train.shape}')
print(f'x_test shape {x_test.shape}')
print(f'y_train shape {y_train.shape}')
print(f'y_test shape {y_test.shape}')

x shape (200, 5)
y shape (200,)
x_train shape (150, 5)
x_test shape (50, 5)
y_train shape (150,)
y_test shape (50,)


In [12]:
#Pembuatan model
from sklearn.naive_bayes import GaussianNB 
model = GaussianNB() 
model.fit(x_train, y_train) 

GaussianNB()

In [13]:
#proses testing
y_pred_train = model.predict(x_train) #testing dataset x_train
y_pred_test = model.predict(x_test) #testing dataset x_test

In [14]:
#evaluasi model
from sklearn.metrics import confusion_matrix,classification_report

print('evaluasi training:')
print(confusion_matrix(y_train, y_pred_train)) 
print(classification_report(y_train, y_pred_train)) 

print('evaluasi testing:')
print(confusion_matrix(y_test, y_pred_test)) 
print(classification_report(y_test, y_pred_test)) 


evaluasi training:
[[46 11  2  6  1]
 [ 0 18  0  0  0]
 [ 0  0 15  0  0]
 [ 0  0  0 13  0]
 [ 1  0  0  0 37]]
              precision    recall  f1-score   support

           0       0.98      0.70      0.81        66
           1       0.62      1.00      0.77        18
           2       0.88      1.00      0.94        15
           3       0.68      1.00      0.81        13
           4       0.97      0.97      0.97        38

    accuracy                           0.86       150
   macro avg       0.83      0.93      0.86       150
weighted avg       0.90      0.86      0.86       150

evaluasi testing:
[[19  2  1  2  1]
 [ 0  5  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  3  0]
 [ 1  0  0  0 15]]
              precision    recall  f1-score   support

           0       0.95      0.76      0.84        25
           1       0.71      1.00      0.83         5
           2       0.50      1.00      0.67         1
           3       0.60      1.00      0.75         3
           4       0.